flask-app-gallery/app/models.py
from flask import current_app, url_for
from app import db

flask-app-gallery/app/__init__.py
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os
from flask import Flask, request, current_app
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_caching import Cache
from config import Config
__version__ = 'v0.0.0'


# TODO: register 'static' folder to app
ROOT = Config.ROOT

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
cache = Cache()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)
    cache.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

flask-app-gallery/app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import errors

flask-app-gallery/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

flask-app-gallery/app/main/routes.py
from app import db, ROOT
from app.main import bp
from app.utils import url_for

from flask import render_template, flash, redirect, request, g, \
    jsonify, current_app, make_response
from json import loads

import os


@bp.before_app_request
def before_request():
    pass

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('index.html', title='Home')

def get_static_json(filename:str):
    """
    Reads filename from /static as json.

    :filename:      str of filename ('data.json')

    returns json.load() obj
    """
    json_path = os.path.join(ROOT, 'app', 'static', filename)
    with open(json_path) as f:
        data = loads(f.read())

        return data

@bp.route('/vrp', methods=['GET', 'POST'])
def vrp():
    if request.method == 'GET':
        data = get_static_json('vrp_origins.json')

    return render_template('vrp.html', data=data)

flask-app-gallery/main.py
from app import create_app, db

app = create_app()

@app.shell_context_processor
def make_shell_context():
    return {'db': db}

flask-app-gallery/app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - flask-gallery{% else %}Under Development{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Flask-Gallery</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.vrp') }}">Vrp</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('main.index') }}">Link</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

flask-app-gallery/app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ 'Hi, you' }}</h1>
{% endblock %}

flask-app-gallery/app/templates/vrp.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block header %}
    <h1>{% block title %}vrp{% endblock %}</h1>
{% endblock %}

{% block app_content %}
    
    <div class="container">
        <div class="row">
            <svg id="origins-map" width="700" height="400"></svg>
        </div>
    </div>

    <script src="https://d3js.org/d3.v5.min.js", charset="utf-8"></script>
    <script src="https://d3js.org/d3-geo-projection.v2.min.js", charset="utf-8"></script>
    <script src="{{ url_for('static', filename='js/vrp.js') }}"></script>
    <script type="text/javascript" charset="utf-8">
        data = {{ data | tojson }}
        plotOrigins(data);
    </script>
{% endblock %}